name: shop_app
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cart: ^0.0.5+1
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/shopping-cart.png"  

flutter:
  uses-material-design: true
  

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    # - images/cash-on-delivery.png
    - images/cash-on-delivery (1).png
    
    


